### ISSUE TITLE
在虚拟机下无法运行

### ISSUE THREAD

**Issue by ratio-dd** [jiafangjun/DD_KaoRou2#4]
mac系统下使用parallels虚拟机运行windows系统
在此虚拟机下会只显示命令提示行，无法正常运行程序
![A77C15EEB48FCC292B03C0AA1FBF80F1](https://user-images.githubusercontent.com/46863569/105731719-a7200e00-5f6a-11eb-9d27-16418a97b373.jpg)

**Comment by HyperSimon** [comment]
你是怎么解决的？
